# encoding: utf-8

#Generates a random phrase
class PhraseGenerator

	def generate i

@phrase = ['{"service":"Twitter","id":"212879154717274113","geo":null,"application":"web","location":null,"date":"Wed Jun 13 12:08:40 +0000 2012","source":"https://twitter.com/Sigohaciendorap/status/212879154717274113","text":"RT @HoneckerRDA: Me siguen los mineros asturianos @PorAsturies  Orgullo de la clase obrera y verdaderos heroes nacionales frente a la ...","description":null,"keywords":"","category":null,"duration":null,"likes":9,"dislikes":null,"favorites":281,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"Sigohaciendorap","real_name":"Ana Poleon Roja","id":"262670183","language":"es","utc":"Athens + 7200","geo":null,"description":"Prefiero !áuna libertad peligrosa a una esclavitud tranquila.","avatar":"https://si0.twimg.com/profile_images/2263582427/conestasqueesmivoz_normal.jpg","location":"","subscribers":625,"subscriptions":1274,"postings":4327,"profile":"https://twitter.com/#!/Sigohaciendorap","website":"http://loquenecesitabas.blogspot.es/"},"links":[],"to_users":[{"name":"HoneckerRDA","id":"555993471","service":"mention","title":null,"thumbnail":null,"href":null},{"name":"PorAsturies","id":"594432676","service":"mention","title":null,"thumbnail":null,"href":null}]}',
		'{"service":"Twitter","id":"212887771839336448","geo":null,"application":"<a href=\"http://blackberry.com/twitter\" rel=\"nofollow\">Twitter for BlackBerry®</a>","location":null,"date":"Wed Jun 13 12:42:54 +0000 2012","source":"https://twitter.com/joaquin_lc/status/212887771839336448","text":"RT @mariadelamiel: (1) Corre el rumor de que el BCE se está planteando rebajar a 0% la rentabilidad que paga a los bancos por los depósi ...","description":null,"keywords":"","category":null,"duration":null,"likes":19,"dislikes":null,"favorites":0,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"joaquin_lc","real_name":"Joaquin Lopez","id":"292605298","language":"es","utc":"Madrid + 3600","geo":null,"description":"Licenciado en Administración y Dirección de Empresas por la UAL - Arbitro territorial de la FABM - Ex banquero-Futuro empresario","avatar":"https://si0.twimg.com/profile_images/1337794252/krillin2_normal.jpg","location":"","subscribers":64,"subscriptions":105,"postings":900,"profile":"https://twitter.com/#!/joaquin_lc","website":null},"links":[],"to_users":[{"name":"mariadelamiel","id":"316058009","service":"mention","title":null,"thumbnail":null,"href":null}]}',
		'{"service":"Twitter","id":null,"geo":null,"application":null,"location":null,"date":null,"source":null,"text":null,"description":null,"keywords":null,"category":null,"duration":null,"likes":null,"dislikes":null,"favorites":null,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":null,"links":[],"to_users":[]}',
		'{"service":"Twitter","id":"212887775740051456","geo":null,"application":"web","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/taciseeger/status/212887775740051456","text":"Vou lavar a louça ;S","description":null,"keywords":"","category":null,"duration":null,"likes":0,"dislikes":null,"favorites":1,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"taciseeger","real_name":"T a c i :)","id":"155252570","language":"pt","utc":"Brasilia + -10800","geo":null,"description":"ℒittℓℯ ℳℴns†ℯr. Deus, Família, Terapia Ocupacional, Dança, Música, Literatura e afins! ♥","avatar":"https://si0.twimg.com/profile_images/2299039753/0vu1ik72xux8lk136qlf_normal.jpeg","location":"Santa Maria, BR","subscribers":861,"subscriptions":772,"postings":11392,"profile":"https://twitter.com/#!/taciseeger","website":"http://www.facebook.com/profile.php?id=100002463339808"},"links":[],"to_users":[]}',
		'{"service":"Twitter","id":"212887775576473600","geo":null,"application":"<a href=\"http://blackberry.com/twitter\" rel=\"nofollow\">Twitter for BlackBerry®</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/Marleenvdk/status/212887775576473600","text":"@JaravdVelden Hahah ik dacht dat vrouwen dat konden ? ;p 2 dingen tegelijk (a) ja mss kan jou oog wel praten.. Hahahahha","description":"212887659675262978","keywords":"","category":null,"duration":null,"likes":0,"dislikes":null,"favorites":0,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"Marleenvdk","real_name":"Marleen","id":"371870304","language":"nl","utc":"Amsterdam + 3600","geo":null,"description":"Ik heb mooie tijden met je gehad, echt waar ! ♥ ik mis je","avatar":"https://si0.twimg.com/profile_images/2229789375/sjklkfdglkdshflkdhsf_20_1__normal.jpg","location":"","subscribers":221,"subscriptions":227,"postings":17285,"profile":"https://twitter.com/#!/Marleenvdk","website":null},"links":[],"to_users":[{"name":"JaravdVelden","id":"309236395","service":"reply","title":"212887659675262978","thumbnail":null,"href":"https://twitter.com/Marleenvdk/status/212887775576473600"}]}',
		'{"service":"Twitter","id":"212887775568084993","geo":null,"application":"<a href=\"http://blackberry.com/twitter\" rel=\"nofollow\">Twitter for BlackBerry®</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/Keilyndguerrero/status/212887775568084993","text":"@MaryAndribelZ hoooy mmm nosee dejame ver mi agenda a ver si esty disponiblee jajaj","description":"212887460135448576","keywords":"","category":null,"duration":null,"likes":0,"dislikes":null,"favorites":4,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"Keilyndguerrero","real_name":"Keilyn Andreina Diaz","id":"145089810","language":"en","utc":"Hawaii + -36000","geo":null,"description":"Centrada en lo q quiero.. No espero nada de nadie..Nada en la vida me sorprende. Calmada y relaxx cero enrollada.. ","avatar":"https://si0.twimg.com/profile_images/2297626739/_Keilhhghhg_normal.jpg","location":"Barinas Venezuela","subscribers":185,"subscriptions":411,"postings":1168,"profile":"https://twitter.com/#!/Keilyndguerrero","website":null},"links":[],"to_users":[{"name":"MaryAndribelZ","id":"209395768","service":"reply","title":"212887460135448576","thumbnail":null,"href":"https://twitter.com/Keilyndguerrero/status/212887775568084993"}]}',
		'{"service":"Twitter","id":"212887775400308738","geo":null,"application":"<a href=\"http://blackberry.com/twitter\" rel=\"nofollow\">Twitter for BlackBerry®</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/Fabiola_chule/status/212887775400308738","text":"RT @jorgesuarezv: AMLO: bajar sueldos a burócratas. ¿Hay mejor fórmula para que aumente la corrupción? ¿Cómo puede gente inteligente apo ...","description":null,"keywords":"","category":null,"duration":null,"likes":8,"dislikes":null,"favorites":0,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"Fabiola_chule","real_name":"Fabiola Nuñez","id":"38903661","language":"en","utc":"Central Time (US & Canada) + -21600","geo":null,"description":"","avatar":"https://si0.twimg.com/profile_images/204664871/fab_normal.JPG","location":"Veracruz, Mexico","subscribers":110,"subscriptions":179,"postings":2197,"profile":"https://twitter.com/#!/Fabiola_chule","website":null},"links":[],"to_users":[{"name":"jorgesuarezv","id":"252254457","service":"mention","title":null,"thumbnail":null,"href":null}]}',
		'{"service":"Twitter","id":"212887775677124609","geo":null,"application":"<a href=\"http://mobile.twitter.com\" rel=\"nofollow\">Mobile Web</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/orensakure/status/212887775677124609","text":"Benzema: Mourinho speaks to me like a father to his son http://t.co/hZLjWCHO","description":null,"keywords":"","category":null,"duration":null,"likes":0,"dislikes":null,"favorites":0,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"orensakure","real_name":"Jeffery Nava","id":"464237294","language":"en","utc":"Chihuahua + -25200","geo":null,"description":"My function in the universe is to analyze complex systems. Then destroy them.","avatar":"https://si0.twimg.com/profile_images/1755485075/406_normal.gif","location":"Boston","subscribers":82,"subscriptions":88,"postings":1447,"profile":"https://twitter.com/#!/orensakure","website":null},"links":[{"service":null,"title":null,"thumbnail":null,"href":"http://t.co/hZLjWCHO"}],"to_users":[]}',
		'{"service":"Twitter","id":"212887775261900800","geo":null,"application":"<a href=\"http://twitter.com/#!/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/billalmaoberry/status/212887775261900800","text":"RT @RealestKidEver: I`m sorry, you are a slut","description":null,"keywords":"","category":null,"duration":null,"likes":88,"dislikes":null,"favorites":13,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"billalmaoberry","real_name":"Azayel Drew Ivashkov","id":"182090280","language":"en","utc":"Quito + -18000","geo":null,"description":"tumblr twitter facebook youtube~ thats what i do all day long and fan girling      and i struggle to focus on my studies         \\(^•^)/","avatar":"https://si0.twimg.com/profile_images/2250782132/image_normal.jpg","location":"my house :)","subscribers":20,"subscriptions":290,"postings":1912,"profile":"https://twitter.com/#!/billalmaoberry","website":"http://www.blueberry-love-cake.tumblr.com"},"links":[],"to_users":[{"name":"RealestKidEver","id":"206388720","service":"mention","title":null,"thumbnail":null,"href":null}]}',
		'{"service":"Twitter","id":"212887775236730880","geo":null,"application":"<a href=\"http://blackberry.com/twitter\" rel=\"nofollow\">Twitter for BlackBerry®</a>","location":null,"date":"Wed Jun 13 12:42:55 +0000 2012","source":"https://twitter.com/SrForeman/status/212887775236730880","text":"RT @PintorcitoBaez: Estamos pensando dividirnos, mandar a un grupo a Sur, con los de la \"barra\" de Nacional! Total igual gritamos todos  ...","description":null,"keywords":"","category":null,"duration":null,"likes":3,"dislikes":null,"favorites":59,"comments":null,"rates":null,"rating":null,"min_rating":null,"max_rating":null,"user":{"name":"SrForeman","real_name":"Santi Lopez","id":"242526374","language":"es","utc":"Buenos Aires + -10800","geo":null,"description":"Fotógrafo - Hijo de Dios, Sarcástico - Amante de la música Electrónica - DJ. Olimpista...\r    PD: no todo lo que tuiteo es cierto..\r    El UF es gratis..\r  ","avatar":"https://si0.twimg.com/profile_images/2303531396/DSC_02411_normal.JPG","location":"","subscribers":2051,"subscriptions":1162,"postings":33123,"profile":"https://twitter.com/#!/SrForeman","website":"https://www.facebook.com/santiagolopezfranco"},"links":[],"to_users":[{"name":"PintorcitoBaez","id":"528068291","service":"mention","title":null,"thumbnail":null,"href":null}]}']

		return @phrase[i]
	end


end