redis:
 db: kermit
 twitter: twitter
 # you must add keys for your own stream implementations
 host: 127.0.0.1
 port: 6379
 password: #Redis password
#Websocket address to publish the statuses
websocket:
 host: 0.0.0.0
 port: 8000
#for each Stream implementation you must define its specific params.
twitter:
 streams: 1
 path: /1/statuses/filter.json
 track: #Keywords you want Twitter tracks and filter the Stream (one for each stream)
  track1: e
 login: KermitPFC
 pass: kermitkermit123123
 port: 443
#RandomPhraseGenerator Stream
rpg: false
#if you want to add more Social Networks/Streams, it can be a good idea to follow the previous Twitter structure.